const AUTH_KEY='bizpilot_accounts';
const SESSION_KEY='bizpilot_session';
const SUB_KEY='bizpilot_subscription';
const KEYS={
 transactions:'bizpilot_transactions',settings:'bizpilot_settings',customers:'bizpilot_customers',inventory:'bizpilot_inventory',
 stock:'bizpilot_stock_movements',invoices:'bizpilot_invoices',staff:'bizpilot_staff',activity:'bizpilot_activity'
};
let transactions=[],customers=[],products=[],stockMovements=[],invoices=[],staff=[],activity=[];
let settings={businessName:'BizPilot',phone:'',email:'',address:'',currency:'KSh',receiptFooter:'Thank you for your business.',defaultLowStock:5,taxRate:0,dailyTarget:0,invoicePrefix:'INV'};
let currentTransactionType='Sale';
const expenseCategories=['Stock','Transport','Rent','Utilities','Airtime / Data','Salaries','Marketing','Other'];
const pageMeta={dashboard:['Dashboard','Your business at a glance'],sales:['Sales','Track money coming into your business'],expenses:['Expenses','Understand where your money is going'],transactions:['Transactions','Everything recorded in BizPilot'],insights:['Business Insights','Turn your numbers into useful decisions'],reports:['Business Reports','Professional summaries ready to print or save as PDF'],inventory:['Inventory','Products, stock levels and movement'],customers:['Customers','Customer records and purchase activity'],invoices:['Invoices & Receipts','Create printable invoices and receipts'],staff:['Staff & Users','Manage your local team records'],pro:['BizPilot Pro','Advanced business tools'],settings:['Settings','Business profile, preferences and backup'],account:['Account','Profile, subscription and access']};
function $(id){return document.getElementById(id)}
function read(key,fallback){try{const v=localStorage.getItem(key);return v?JSON.parse(v):fallback}catch(e){return fallback}}
function write(key,value){localStorage.setItem(key,JSON.stringify(value))}
function uid(prefix='id'){return prefix+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7)}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function money(n){return `${settings.currency||'KSh'} ${Number(n||0).toLocaleString('en-KE',{maximumFractionDigits:2})}`}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtDate(s){if(!s)return '—';const d=new Date(s+'T00:00:00');return Number.isNaN(d.getTime())?s:d.toLocaleDateString('en-KE',{day:'numeric',month:'short',year:'numeric'})}
function loadAll(){
 transactions=Array.isArray(read(KEYS.transactions,[]))?read(KEYS.transactions,[]):[];
 customers=Array.isArray(read(KEYS.customers,[]))?read(KEYS.customers,[]):[];
 products=Array.isArray(read(KEYS.inventory,[]))?read(KEYS.inventory,[]):[];
 stockMovements=Array.isArray(read(KEYS.stock,[]))?read(KEYS.stock,[]):[];
 invoices=Array.isArray(read(KEYS.invoices,[]))?read(KEYS.invoices,[]):[];
 staff=Array.isArray(read(KEYS.staff,[]))?read(KEYS.staff,[]):[];
 activity=Array.isArray(read(KEYS.activity,[]))?read(KEYS.activity,[]):[];
 const s=read(KEYS.settings,null);if(s&&typeof s==='object')settings={...settings,...s};
 transactions=transactions.map(t=>({...t,category:t.type==='Expense'?(t.category||'Other'):t.category||'',quantity:t.quantity||null}));
 products=products.map(p=>({...p,lowStock:Number(p.lowStock??settings.defaultLowStock),stock:Number(p.stock||0),buyingPrice:Number(p.buyingPrice||0),sellingPrice:Number(p.sellingPrice||0)}));
}
function logActivity(action,detail){activity.unshift({id:uid('act'),action,detail,createdAt:new Date().toISOString()});activity=activity.slice(0,300);write(KEYS.activity,activity)}
function showPage(id,button){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active-page'));$(id)?.classList.add('active-page');document.querySelectorAll('.nav-item').forEach(b=>b.classList.remove('active'));if(button?.classList.contains('nav-item'))button.classList.add('active');else{const b=[...document.querySelectorAll('.nav-item')].find(x=>x.getAttribute('onclick')?.includes(`'${id}'`));b?.classList.add('active')}if(pageMeta[id]){$('pageTitle').textContent=pageMeta[id][0];$('pageSubtitle').textContent=pageMeta[id][1]}updatePage(id);window.scrollTo({top:0,behavior:'smooth'})}
function updatePage(id){if(id==='account')renderAccount();if(id==='dashboard')renderDashboard();if(id==='sales')renderSales();if(id==='expenses')renderExpenses();if(id==='transactions')renderTransactions();if(id==='insights')renderInsights();if(id==='reports')renderReports();if(id==='inventory'){renderInventory();renderStockHistory()}if(id==='customers')renderCustomers();if(id==='invoices')renderInvoices();if(id==='staff')renderStaff();if(id==='pro')renderPro();if(id==='settings')renderSettings()}
function updateEverything(){renderAccount();renderDashboard();renderSales();renderExpenses();renderTransactions();renderInsights();renderReports();renderInventory();renderStockHistory();renderCustomers();renderInvoices();renderStaff();renderPro();renderSettings();populateSelects()}
function getSales(){return transactions.filter(t=>t.type==='Sale')}
function getExpenses(){return transactions.filter(t=>t.type==='Expense')}
function sum(list){return list.reduce((a,t)=>a+Number(t.amount||0),0)}
function profit(){return sum(getSales())-sum(getExpenses())}
function periodTransactions(from,to){return transactions.filter(t=>(!from||t.date>=from)&&(!to||t.date<=to))}
function recommendation(list=transactions){const sales=sum(list.filter(t=>t.type==='Sale')),expenses=sum(list.filter(t=>t.type==='Expense')),p=sales-expenses;if(!list.length)return 'Record a few sales and expenses to unlock a useful business recommendation.';if(sales===0)return 'You have spending recorded but no sales yet. Focus on revenue-generating activity and keep essential costs controlled.';if(p<0)return 'Your recorded expenses are higher than revenue. Review the largest expense categories and protect cash flow before adding non-essential costs.';if(expenses>sales*.6)return 'Expenses are taking a large share of revenue. Review recurring costs and high-spend categories for savings opportunities.';if(sales>0&&p/sales>=.3)return 'Your current recorded margin is healthy. Consider increasing repeat sales while protecting the costs that drive revenue.';return 'Your business is profitable on the recorded data. Keep tracking consistently so you can spot trends early.'}
function renderDashboard(){const t=today(),s=getSales().filter(x=>x.date===t),e=getExpenses().filter(x=>x.date===t),sv=sum(s),ev=sum(e),p=sv-ev;const low=products.filter(x=>Number(x.stock)<=Number(x.lowStock??settings.defaultLowStock));$('todaySales').textContent=money(sv);$('todayExpenses').textContent=money(ev);$('todayProfit').textContent=money(p);$('todaySalesCount').textContent=`${s.length} sale${s.length===1?'':'s'}`;$('todayExpenseCount').textContent=`${e.length} expense${e.length===1?'':'s'}`;$('dashLowStock').textContent=low.length;$('dashLowStockText').textContent=low.length?`${low.map(x=>x.name).slice(0,2).join(', ')}${low.length>2?'…':''}`:'All stock healthy';$('dashRevenue').textContent=money(sum(getSales()));$('dashProfit').textContent=money(profit());$('dashboardInsight').textContent=recommendation();const a=$('alertStrip');if(low.length){a.classList.remove('hidden');a.innerHTML=`<strong>Low stock:</strong> ${esc(low.map(x=>`${x.name} (${x.stock})`).join(', '))}`;}else a.classList.add('hidden');renderBars($('performanceChart'),7);$('recentTransactions').innerHTML=renderTransactionRows(transactions.slice().sort((a,b)=>new Date(b.createdAt||b.date)-new Date(a.createdAt||a.date)).slice(0,6))}
function renderBars(el,days=7,list=transactions){if(!el)return;const end=new Date();const rows=[];for(let i=days-1;i>=0;i--){const d=new Date(end);d.setDate(end.getDate()-i);const ds=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;const sales=sum(list.filter(t=>t.date===ds&&t.type==='Sale')),exp=sum(list.filter(t=>t.date===ds&&t.type==='Expense'));rows.push({ds,sales,exp})}const max=Math.max(1,...rows.flatMap(r=>[r.sales,r.exp]));el.innerHTML=rows.map(r=>`<div class="chart-day"><div class="bar-pair"><div class="bar" title="Sales ${esc(money(r.sales))}" style="height:${Math.max(2,r.sales/max*150)}px"></div><div class="bar expense" title="Expenses ${esc(money(r.exp))}" style="height:${Math.max(2,r.exp/max*150)}px"></div></div><small>${new Date(r.ds+'T00:00:00').toLocaleDateString('en-KE',{weekday:'short'}).slice(0,3)}</small></div>`).join('')+`<div class="chart-legend">■ Sales &nbsp; <span>■ Expenses</span></div>`}
function renderTransactionRows(list){if(!list.length)return '<div class="empty-state">No transactions yet.</div>';return list.map(t=>`<div class="transaction-item"><div><strong>${esc(t.name||'Transaction')}</strong><span>${fmtDate(t.date)}${t.category?' · '+esc(t.category):''}${t.customerId?' · '+esc(customers.find(c=>String(c.id)===String(t.customerId))?.name||'Customer'):''}</span></div><div class="transaction-amount ${t.type==='Expense'?'expense':'sale'}">${t.type==='Expense'?'-':'+'}${money(t.amount)}</div><div class="transaction-type">${esc(t.type)}</div></div>`).join('')}
function renderSales(){const list=getSales().slice().sort((a,b)=>new Date(b.createdAt||b.date)-new Date(a.createdAt||a.date));const q=($('salesSearch')?.value||'').toLowerCase();const f=list.filter(t=>`${t.name} ${t.note||''}`.toLowerCase().includes(q));$('salesTotal').textContent=money(sum(list));$('salesCount').textContent=list.length;$('salesAverage').textContent=money(list.length?sum(list)/list.length:0);$('salesHistory').innerHTML=renderTransactionRows(f)}
function renderExpenses(){const list=getExpenses().slice().sort((a,b)=>new Date(b.createdAt||b.date)-new Date(a.createdAt||a.date));const q=($('expenseSearch')?.value||'').toLowerCase();const f=list.filter(t=>`${t.name} ${t.category||''} ${t.note||''}`.toLowerCase().includes(q));$('expensesTotal').textContent=money(sum(list));$('expensesCount').textContent=list.length;$('expensesAverage').textContent=money(list.length?sum(list)/list.length:0);const cats={};list.forEach(t=>cats[t.category||'Other']=(cats[t.category||'Other']||0)+Number(t.amount||0));$('categoryBreakdown').innerHTML=Object.entries(cats).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="category-row"><div><strong>${esc(k)}</strong><span>${money(v)}</span></div><div class="category-bar"><span style="width:${sum(list)?Math.max(2,v/sum(list)*100):0}%"></span></div></div>`).join('')||'<div class="empty-state">No expenses recorded yet.</div>';$('expenseHistory').innerHTML=renderTransactionRows(f)}
function renderTransactions(){let list=transactions.slice().sort((a,b)=>new Date(b.createdAt||b.date)-new Date(a.createdAt||a.date));const q=($('transactionSearch')?.value||'').toLowerCase(),type=$('transactionFilter')?.value||'all';list=list.filter(t=>(type==='all'||t.type===type)&&`${t.name} ${t.note||''} ${t.category||''}`.toLowerCase().includes(q));$('allTransactions').innerHTML=renderTransactionRows(list)}
function renderInsights(){let from=$('insightFrom')?.value||'',to=$('insightTo')?.value||'';const list=periodTransactions(from,to),sales=list.filter(t=>t.type==='Sale'),expenses=list.filter(t=>t.type==='Expense'),rev=sum(sales),sp=sum(expenses),p=rev-sp;$('insightRevenue').textContent=money(rev);$('insightSpending').textContent=money(sp);$('insightProfit').textContent=money(p);$('profitMargin').textContent=rev?`${(p/rev*100).toFixed(1)}%`:'0%';$('spendingRatio').textContent=rev?`${(sp/rev*100).toFixed(1)}%`:'0%';const byDay={};sales.forEach(t=>byDay[t.date]=(byDay[t.date]||0)+Number(t.amount||0));const best=Object.entries(byDay).sort((a,b)=>b[1]-a[1])[0];$('bestSalesDay').textContent=best?`${fmtDate(best[0])} · ${money(best[1])}`:'—';const cats={};expenses.forEach(t=>cats[t.category||'Other']=(cats[t.category||'Other']||0)+Number(t.amount||0));const topCat=Object.entries(cats).sort((a,b)=>b[1]-a[1])[0];$('topExpenseCategory').textContent=topCat?`${topCat[0]} · ${money(topCat[1])}`:'—';const cr={};sales.forEach(t=>{if(t.customerId){const c=customers.find(x=>String(x.id)===String(t.customerId));if(c)cr[c.id]=(cr[c.id]||0)+Number(t.amount||0)}});const topC=Object.entries(cr).sort((a,b)=>b[1]-a[1])[0],topCustomer=topC?customers.find(c=>String(c.id)===String(topC[0])):null;$('topCustomerInsight').textContent=topCustomer?`${topCustomer.name} · ${money(topC[1])}`:'—';$('businessInsight').textContent=recommendation(list);renderBars($('insightChart'),7,list);renderProductAnalytics(sales);renderCustomerAnalytics(sales)}
function renderProductAnalytics(sales){const map={};sales.forEach(t=>{if(t.productId){const p=products.find(x=>String(x.id)===String(t.productId));const name=p?.name||t.productName||'Deleted product';if(!map[name])map[name]={qty:0,revenue:0};map[name].qty+=Number(t.quantity||1);map[name].revenue+=Number(t.amount||0)}});const rows=Object.entries(map).sort((a,b)=>b[1].revenue-a[1].revenue).slice(0,10);$('productAnalytics').innerHTML=rows.length?`<div class="table-row head"><span>Product</span><span>Qty</span><span>Revenue</span><span></span></div>`+rows.map(([n,v])=>`<div class="table-row"><span>${esc(n)}</span><span>${v.qty}</span><span>${money(v.revenue)}</span><span></span></div>`).join(''):'<div class="empty-state">No product-linked sales yet.</div>'}
function renderCustomerAnalytics(sales){const map={};sales.forEach(t=>{if(t.customerId){const c=customers.find(x=>String(x.id)===String(t.customerId));if(c){if(!map[c.id])map[c.id]={name:c.name,qty:0,revenue:0};map[c.id].qty++;map[c.id].revenue+=Number(t.amount||0)}}});const rows=Object.values(map).sort((a,b)=>b.revenue-a.revenue).slice(0,10);$('customerAnalytics').innerHTML=rows.length?`<div class="table-row head"><span>Customer</span><span>Purchases</span><span>Revenue</span><span></span></div>`+rows.map(v=>`<div class="table-row"><span>${esc(v.name)}</span><span>${v.qty}</span><span>${money(v.revenue)}</span><span></span></div>`).join(''):'<div class="empty-state">No customer-linked sales yet.</div>'}
function renderReports(){const sales=getSales(),exp=getExpenses(),rev=sum(sales),sp=sum(exp);$('reportBusinessName').textContent=`${(settings.businessName||'BizPilot').toUpperCase()} BUSINESS REPORT`;$('reportDate').textContent=new Date().toLocaleString('en-KE',{dateStyle:'medium',timeStyle:'short'});$('reportRevenue').textContent=money(rev);$('reportSpending').textContent=money(sp);$('reportProfit').textContent=money(rev-sp);$('reportMargin').textContent=rev?`${((rev-sp)/rev*100).toFixed(1)}%`:'0%';$('reportSalesCount').textContent=sales.length;$('reportExpenseCount').textContent=exp.length;$('reportCustomerCount').textContent=customers.length;$('reportInventoryValue').textContent=money(products.reduce((a,p)=>a+Number(p.stock||0)*Number(p.buyingPrice||0),0));const days={};sales.forEach(t=>days[t.date]=(days[t.date]||0)+Number(t.amount||0));const best=Object.entries(days).sort((a,b)=>b[1]-a[1])[0];$('reportBestDay').textContent=best?`${fmtDate(best[0])} · ${money(best[1])}`:'—';const cats={};exp.forEach(t=>cats[t.category||'Other']=(cats[t.category||'Other']||0)+Number(t.amount||0));const top=Object.entries(cats).sort((a,b)=>b[1]-a[1])[0];$('reportTopCategory').textContent=top?`${top[0]} · ${money(top[1])}`:'—';$('reportCategories').innerHTML=Object.entries(cats).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="report-row"><span>${esc(k)}</span><strong>${money(v)}</strong></div>`).join('')||'<div class="empty-state">No expenses recorded.</div>';$('reportInsight').textContent=recommendation()}
function renderInventory(){const listEl=$('inventoryList');const q=($('inventorySearch')?.value||'').toLowerCase();const filtered=products.filter(p=>`${p.name} ${p.notes||''}`.toLowerCase().includes(q));const value=products.reduce((a,p)=>a+Number(p.stock||0)*Number(p.buyingPrice||0),0),low=products.filter(p=>Number(p.stock)<=Number(p.lowStock??settings.defaultLowStock)),pot=products.reduce((a,p)=>a+Number(p.stock||0)*Math.max(0,Number(p.sellingPrice||0)-Number(p.buyingPrice||0)),0);$('inventoryProductCount').textContent=products.length;$('inventoryValue').textContent=money(value);$('inventoryLowStock').textContent=low.length;$('inventoryPotentialProfit').textContent=money(pot);listEl.innerHTML=filtered.length?filtered.map(p=>{const isLow=Number(p.stock)<=Number(p.lowStock??settings.defaultLowStock);return `<div class="inventory-item"><div class="inventory-main"><div class="inventory-avatar">▦</div><div class="inventory-info"><strong>${esc(p.name)}</strong><span>${isLow?'Low stock':'In stock'}${p.notes?' · '+esc(p.notes):''}</span></div></div><div class="inventory-stats"><div><span>Stock</span><strong class="${isLow?'stock-low':'stock-ok'}">${p.stock}</strong></div><div><span>Buy</span><strong>${money(p.buyingPrice)}</strong></div><div><span>Sell</span><strong>${money(p.sellingPrice)}</strong></div><div><span>Value</span><strong>${money(Number(p.stock)*Number(p.buyingPrice))}</strong></div></div><div class="inventory-actions"><button class="secondary-btn" onclick="openStockModal('${esc(p.id)}')">Stock</button><button class="secondary-btn" onclick="openProductModal('${esc(p.id)}')">Edit</button><button class="danger-btn" onclick="deleteProduct('${esc(p.id)}')">Delete</button></div></div>`}).join(''):'<div class="empty-state">No products match your search.</div>'}
function renderStockHistory(){const f=$('stockHistoryFilter')?.value||'all';let list=stockMovements.slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));if(f!=='all')list=list.filter(m=>m.type===f);$('stockHistoryList').innerHTML=list.length?list.slice(0,200).map(m=>`<div class="transaction-item"><div><strong>${esc(m.productName||'Product')}</strong><span>${esc(m.note||'No note')} · ${new Date(m.createdAt).toLocaleString('en-KE')}</span></div><div class="transaction-amount">${m.delta>0?'+':''}${m.delta}</div><div class="transaction-type">${esc(m.type)} · ${m.before} → ${m.after}</div></div>`).join(''):'<div class="empty-state">No stock movements yet.</div>'}
function renderCustomers(){const q=($('customerSearch')?.value||'').toLowerCase();const filtered=customers.filter(c=>`${c.name} ${c.phone||''} ${c.email||''}`.toLowerCase().includes(q));const stats=customers.map(c=>customerStats(c.id));$('customerCount').textContent=customers.length;$('customerRevenue').textContent=money(stats.reduce((a,x)=>a+x.revenue,0));$('activeCustomerCount').textContent=customers.filter(c=>(c.status||'Active')==='Active').length;$('repeatCustomerCount').textContent=stats.filter(x=>x.count>1).length;$('customerList').innerHTML=filtered.length?filtered.map(c=>{const s=customerStats(c.id);return `<div class="customer-item"><div><strong>${esc(c.name)}</strong><div class="customer-meta"><span>${esc(c.phone||'No phone')}</span><span>${esc(c.email||'No email')}</span><span class="status-pill">${esc(c.status||'Active')}</span></div></div><div><strong>${money(s.revenue)}</strong><div class="customer-meta"><span>${s.count} purchase${s.count===1?'':'s'}</span><span>Last: ${fmtDate(s.last)}</span></div></div><div class="customer-actions"><button class="secondary-btn" onclick="openCustomerModal('${esc(c.id)}')">Edit</button><button class="danger-btn" onclick="deleteCustomer('${esc(c.id)}')">Delete</button></div></div>`}).join(''):'<div class="empty-state">No customers found.</div>'}
function customerStats(id){const s=getSales().filter(t=>String(t.customerId)===String(id));return {count:s.length,revenue:sum(s),last:s.map(x=>x.date).sort().reverse()[0]||''}}
function renderInvoices(){const q=($('invoiceSearch')?.value||'').toLowerCase();const list=invoices.filter(i=>`${i.number} ${i.customerName||''}`.toLowerCase().includes(q));$('invoiceCount').textContent=invoices.length;$('invoiceValue').textContent=money(invoices.reduce((a,i)=>a+Number(i.total||0),0));$('invoicePaid').textContent=money(invoices.filter(i=>i.status==='Paid').reduce((a,i)=>a+Number(i.total||0),0));$('invoiceList').innerHTML=list.length?list.slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).map(i=>`<div class="invoice-item"><div><strong>${esc(i.number)}</strong><div class="customer-meta"><span>${fmtDate(i.date)}</span><span>${esc(i.customerName||'Walk-in')}</span><span class="status-pill">${esc(i.status)}</span></div></div><div class="invoice-summary"><strong>${money(i.total)}</strong><div>${esc((i.items||[]).map(x=>`${x.name} × ${x.qty}`).join(', '))}</div></div><div class="invoice-actions"><button class="secondary-btn" onclick="printInvoice('${esc(i.id)}')">Print</button><button class="danger-btn" onclick="deleteInvoice('${esc(i.id)}')">Delete</button></div></div>`).join(''):'<div class="empty-state">No invoices yet.</div>'}
function renderStaff(){const active=staff.filter(s=>s.status==='Active');$('staffCount').textContent=staff.length;$('activeStaffCount').textContent=active.length;$('managerCount').textContent=staff.filter(s=>s.role==='Manager'||s.role==='Owner').length;$('staffList').innerHTML=staff.length?staff.map(s=>`<div class="staff-item"><div><strong>${esc(s.name)}</strong><div class="staff-meta"><span>${esc(s.role)}</span><span>${esc(s.phone||'No phone')}</span><span class="status-pill">${esc(s.status)}</span></div></div><div>${esc(s.notes||'')}</div><div class="staff-actions"><button class="secondary-btn" onclick="openStaffModal('${esc(s.id)}')">Edit</button><button class="danger-btn" onclick="deleteStaff('${esc(s.id)}')">Delete</button></div></div>`).join(''):'<div class="empty-state">No staff records yet.</div>'}
function renderPro(){const sub=getSubscription();const active=isProActive();$('proPlanBadge').textContent=active?'PRO PLAN':'FREE PLAN';if($('accountPlanBadge'))$('accountPlanBadge').textContent=active?'PRO PLAN':'FREE PLAN';if($('subscriptionStatus'))$('subscriptionStatus').textContent=active?`Pro ${sub.plan||''} plan is active`:'Free plan — upgrade to unlock BizPilot Pro';if(!active){$('proAverageSale').textContent='Locked';$('proTopProduct').textContent='Locked';$('proTopCustomer').textContent='Locked';$('proStockValue').textContent='Locked';$('proAnalysis').innerHTML='<div class="insight-box">Your Pro workspace is ready. Choose Monthly or Annual on the Account page to start checkout. Pro access is activated only after payment verification.</div>';if($('proAnalysisSubtitle'))$('proAnalysisSubtitle').textContent='Available with an active Pro subscription.';return}if($('proAnalysisSubtitle'))$('proAnalysisSubtitle').textContent=`Active ${sub.plan||'Pro'} plan · ${sub.expiresAt?`expires ${fmtDate(String(sub.expiresAt).slice(0,10))}`:'active'}`;const sales=getSales();$('proAverageSale').textContent=money(sales.length?sum(sales)/sales.length:0);const pm={};sales.forEach(t=>{if(t.productId){const p=products.find(x=>String(x.id)===String(t.productId));const n=p?.name||t.productName||'Deleted product';pm[n]=(pm[n]||0)+Number(t.amount||0)}});const topP=Object.entries(pm).sort((a,b)=>b[1]-a[1])[0];$('proTopProduct').textContent=topP?topP[0]:'—';const cm={};sales.forEach(t=>{if(t.customerId){const c=customers.find(x=>String(x.id)===String(t.customerId));if(c)cm[c.name]=(cm[c.name]||0)+Number(t.amount||0)}});const topC=Object.entries(cm).sort((a,b)=>b[1]-a[1])[0];$('proTopCustomer').textContent=topC?topC[0]:'—';$('proStockValue').textContent=money(products.reduce((a,p)=>a+Number(p.stock)*Number(p.buyingPrice),0));$('proAnalysis').textContent=recommendation()}
function renderSettings(){$('businessNameInput').value=settings.businessName||'';$('businessPhoneInput').value=settings.phone||'';$('businessEmailInput').value=settings.email||'';$('businessAddressInput').value=settings.address||'';$('currencyInput').value=settings.currency||'KSh';$('receiptFooterInput').value=settings.receiptFooter||'';$('defaultLowStockInput').value=settings.defaultLowStock??5;$('taxRateInput').value=settings.taxRate??0;$('dailyTargetInput').value=settings.dailyTarget??0;$('invoicePrefixInput').value=settings.invoicePrefix||'INV';}
function populateSelects(){const c=$('transactionCustomer'),ic=$('invoiceCustomer'),ss=$('transactionStaff'),ps=$('transactionProduct'),sp=$('stockProduct');if(c)c.innerHTML='<option value="">Walk-in / Unassigned</option>'+customers.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');if(ic)ic.innerHTML='<option value="">Walk-in / Unassigned</option>'+customers.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');if(ss)ss.innerHTML='<option value="">Owner / Unassigned</option>'+staff.filter(x=>x.status==='Active').map(x=>`<option value="${esc(x.id)}">${esc(x.name)} · ${esc(x.role)}</option>`).join('');if(ps){const cur=ps.value;ps.innerHTML='<option value="">Manual sale / service</option>'+products.map(p=>`<option value="${esc(p.id)}" ${Number(p.stock)<=0?'disabled':''}>${esc(p.name)} — ${money(p.sellingPrice)} (${p.stock} in stock)</option>`).join('');ps.value=cur}if(sp){const cur=sp.value;sp.innerHTML=products.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} (${p.stock})</option>`).join('');if(cur)sp.value=cur;updateStockCurrent()}$('amountCurrency').textContent=settings.currency||'KSh'}
function openTransactionModal(type){currentTransactionType=type;$('transactionType').value=type;$('modalTitle').textContent=type==='Sale'?'Add Sale':'Add Expense';$('transactionName').value='';$('transactionAmount').value='';$('transactionDate').value=today();$('transactionNote').value='';$('transactionCategory').value='Other';$('transactionProduct').value='';$('transactionCustomer').value='';$('transactionStaff').value='';$('transactionQuantity').value=1;$('categoryField').classList.toggle('hidden-field',type!=='Expense');$('customerField').classList.toggle('hidden-field',type!=='Sale');$('inventorySaleField').classList.toggle('hidden-field',type!=='Sale');$('saleQuantityField').classList.add('hidden-field');$('transactionAmount').readOnly=false;populateSelects();$('transactionModal').classList.add('show');setTimeout(()=>$('transactionName').focus(),100)}
function closeTransactionModal(){$('transactionModal').classList.remove('show')}
function handleProductSelection(){const p=products.find(x=>String(x.id)===String($('transactionProduct').value));if(!p){$('saleQuantityField').classList.add('hidden-field');$('transactionAmount').readOnly=false;return}$('saleQuantityField').classList.remove('hidden-field');$('transactionName').value=p.name;$('transactionAmount').readOnly=true;updateSaleAmountFromProduct()}
function updateSaleAmountFromProduct(){const p=products.find(x=>String(x.id)===String($('transactionProduct').value));if(!p)return;const q=Math.max(1,Math.floor(Number($('transactionQuantity').value)||1));$('transactionAmount').value=(Number(p.sellingPrice)*q).toFixed(2)}
function submitTransaction(e){e.preventDefault();const type=$('transactionType').value,name=$('transactionName').value.trim(),date=$('transactionDate').value,category=type==='Expense'?$('transactionCategory').value:'',note=$('transactionNote').value.trim(),customerId=type==='Sale'?$('transactionCustomer').value:'',staffId=$('transactionStaff').value,productId=type==='Sale'?$('transactionProduct').value:'',qty=productId?Math.max(1,Math.floor(Number($('transactionQuantity').value)||1)):null;let amount=Number($('transactionAmount').value);const p=productId?products.find(x=>String(x.id)===String(productId)):null;if(p){if(qty>Number(p.stock))return alert(`Not enough stock. ${p.name} has ${p.stock} in stock.`);amount=Number(p.sellingPrice)*qty}if(!name||!date||!Number.isFinite(amount)||amount<=0)return alert('Please enter valid transaction details.');const t={id:uid('tx'),type,name,amount,date,note,category,customerId,productId,productName:p?.name||'',quantity:qty,staffId,createdAt:new Date().toISOString()};transactions.unshift(t);if(p){const before=Number(p.stock);p.stock=Math.max(0,before-qty);addStockMovement(p,'Sale',-qty,before,p.stock,`Sale recorded: ${name}`)}write(KEYS.transactions,transactions);write(KEYS.inventory,products);logActivity(`Added ${type}`,`${name} · ${money(amount)}`);closeTransactionModal();updateEverything()}
function openProductModal(id=''){const f=$('productModal');$('productEditId').value=id||'';$('productModalTitle').textContent=id?'Edit Product':'Add Product';if(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return;$('productName').value=p.name;$('productStock').value=p.stock;$('productBuyingPrice').value=p.buyingPrice;$('productSellingPrice').value=p.sellingPrice;$('productLowStock').value=p.lowStock??settings.defaultLowStock;$('productNotes').value=p.notes||''}else{$('productName').value='';$('productStock').value=0;$('productBuyingPrice').value=0;$('productSellingPrice').value=0;$('productLowStock').value=settings.defaultLowStock??5;$('productNotes').value=''}f.classList.add('show');setTimeout(()=>$('productName').focus(),100)}
function closeProductModal(){$('productModal').classList.remove('show')}
function saveProduct(e){e.preventDefault();const id=$('productEditId').value,name=$('productName').value.trim(),stock=Math.max(0,Math.floor(Number($('productStock').value))),buy=Math.max(0,Number($('productBuyingPrice').value)),sell=Math.max(0,Number($('productSellingPrice').value)),low=Math.max(0,Math.floor(Number($('productLowStock').value))),notes=$('productNotes').value.trim();if(!name||![stock,buy,sell,low].every(Number.isFinite))return alert('Please enter valid product details.');if(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return;const before=Number(p.stock);p.name=name;p.stock=stock;p.buyingPrice=buy;p.sellingPrice=sell;p.lowStock=low;p.notes=notes;p.updatedAt=new Date().toISOString();if(stock!==before)addStockMovement(p,'Adjustment',stock-before,before,stock,'Stock changed while editing product')}else{const p={id:uid('prd'),name,stock,buyingPrice:buy,sellingPrice:sell,lowStock:low,notes,createdAt:new Date().toISOString()};products.unshift(p);if(stock>0)addStockMovement(p,'Restock',stock,0,stock,'Opening stock')};write(KEYS.inventory,products);logActivity(id?'Edited product':'Added product',name);closeProductModal();updateEverything()}
function deleteProduct(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return;if(!confirm(`Delete ${p.name}? Historical sales and stock history will remain.`))return;products=products.filter(x=>String(x.id)!==String(id));write(KEYS.inventory,products);logActivity('Deleted product',p.name);updateEverything()}
function addStockMovement(p,type,delta,before,after,note){stockMovements.unshift({id:uid('mov'),productId:p.id,productName:p.name,type,delta,before,after,quantity:Math.abs(delta),note,createdAt:new Date().toISOString()});write(KEYS.stock,stockMovements);}
function openStockModal(id=''){populateSelects();if(id)$('stockProduct').value=id;updateStockCurrent();$('stockType').value='Restock';$('stockQuantity').value='1';$('stockNote').value='';$('stockModal').classList.add('show')}
function closeStockModal(){$('stockModal').classList.remove('show')}
function updateStockCurrent(){const p=products.find(x=>String(x.id)===String($('stockProduct').value));$('stockCurrent').textContent=`Current stock: ${p?p.stock:0}`;$('stockQuantityLabel').lastElementChild.min=$('stockType').value==='Adjustment'?'0':'1'}
function saveStockMovement(e){e.preventDefault();const p=products.find(x=>String(x.id)===String($('stockProduct').value));if(!p)return alert('Select a product.');const type=$('stockType').value,n=Math.max(0,Math.floor(Number($('stockQuantity').value))),note=$('stockNote').value.trim(),before=Number(p.stock);let after=before,delta=0;if(type==='Restock'){if(n<1)return alert('Enter a quantity.');after=before+n;delta=n}else if(type==='Remove'){if(n<1||n>before)return alert('Enter a valid quantity to remove.');after=before-n;delta=-n}else{after=n;delta=after-before}p.stock=after;addStockMovement(p,type==='Remove'?'Adjustment':type,delta,before,after,note||`${type} stock`);write(KEYS.inventory,products);logActivity('Stock movement',`${p.name}: ${before} → ${after}`);closeStockModal();updateEverything()}
function openCustomerModal(id=''){ $('customerEditId').value=id||'';$('customerModalTitle').textContent=id?'Edit Customer':'Add Customer';if(id){const c=customers.find(x=>String(x.id)===String(id));if(!c)return;$('customerName').value=c.name;$('customerPhone').value=c.phone||'';$('customerEmail').value=c.email||'';$('customerStatus').value=c.status||'Active';$('customerNotes').value=c.notes||''}else{$('customerName').value='';$('customerPhone').value='';$('customerEmail').value='';$('customerStatus').value='Active';$('customerNotes').value=''}$('customerModal').classList.add('show')}
function closeCustomerModal(){$('customerModal').classList.remove('show')}
function saveCustomer(e){e.preventDefault();const id=$('customerEditId').value,name=$('customerName').value.trim();if(!name)return alert('Customer name is required.');const data={name,phone:$('customerPhone').value.trim(),email:$('customerEmail').value.trim(),status:$('customerStatus').value,notes:$('customerNotes').value.trim(),updatedAt:new Date().toISOString()};if(id){const c=customers.find(x=>String(x.id)===String(id));Object.assign(c,data)}else{customers.unshift({id:uid('cus'),...data,createdAt:new Date().toISOString()})}write(KEYS.customers,customers);logActivity(id?'Edited customer':'Added customer',name);closeCustomerModal();updateEverything()}
function deleteCustomer(id){const c=customers.find(x=>String(x.id)===String(id));if(!c)return;if(!confirm(`Delete ${c.name}? Historical sales will remain.`))return;customers=customers.filter(x=>String(x.id)!==String(id));write(KEYS.customers,customers);logActivity('Deleted customer',c.name);updateEverything()}
function addInvoiceItem(data={}){const wrap=$('invoiceItems'),row=document.createElement('div');row.className='invoice-line';row.innerHTML=`<input class="inv-name" maxlength="100" placeholder="Item / service" value="${esc(data.name||'')}"><input class="inv-qty" type="number" min="1" step="1" value="${data.qty||1}"><input class="inv-price" type="number" min="0" step="0.01" value="${data.price||0}"><button type="button" class="danger-btn" onclick="this.parentElement.remove();updateInvoiceTotals()">×</button>`;row.querySelectorAll('input').forEach(x=>x.addEventListener('input',updateInvoiceTotals));wrap.appendChild(row);updateInvoiceTotals()}
function openInvoiceModal(){ $('invoiceDate').value=today();$('invoiceNotes').value='';$('invoiceStatus').value='Paid';populateSelects();$('invoiceCustomer').value='';$('invoiceItems').innerHTML='';addInvoiceItem();$('invoiceModal').classList.add('show')}
function closeInvoiceModal(){$('invoiceModal').classList.remove('show')}
function updateInvoiceTotals(){const rows=[...document.querySelectorAll('.invoice-line')];const sub=rows.reduce((a,r)=>a+Number(r.querySelector('.inv-qty').value||0)*Number(r.querySelector('.inv-price').value||0),0),tax=sub*(Number(settings.taxRate||0)/100),total=sub+tax;$('invoiceSubtotal').textContent=money(sub);$('invoiceTax').textContent=money(tax);$('invoiceTotal').textContent=money(total);return{sub,tax,total}}
function nextInvoiceNumber(){const prefix=settings.invoicePrefix||'INV';return `${prefix}-${String(invoices.length+1).padStart(4,'0')}`}
function saveInvoice(e){e.preventDefault();const rows=[...document.querySelectorAll('.invoice-line')].map(r=>({name:r.querySelector('.inv-name').value.trim(),qty:Math.max(1,Number(r.querySelector('.inv-qty').value||1)),price:Math.max(0,Number(r.querySelector('.inv-price').value||0))})).filter(x=>x.name&&x.price>0);if(!rows.length)return alert('Add at least one priced item.');const totals=updateInvoiceTotals(),c=customers.find(x=>String(x.id)===String($('invoiceCustomer').value));const inv={id:uid('inv'),number:nextInvoiceNumber(),date:$('invoiceDate').value,customerId:c?.id||'',customerName:c?.name||'Walk-in / Unassigned',items:rows,subtotal:totals.sub,tax:totals.tax,total:totals.total,status:$('invoiceStatus').value,notes:$('invoiceNotes').value.trim(),createdAt:new Date().toISOString()};invoices.unshift(inv);write(KEYS.invoices,invoices);logActivity('Created invoice',`${inv.number} · ${money(inv.total)}`);closeInvoiceModal();updateEverything();printInvoice(inv.id)}
function deleteInvoice(id){const i=invoices.find(x=>String(x.id)===String(id));if(!i)return;if(!confirm(`Delete ${i.number}?`))return;invoices=invoices.filter(x=>String(x.id)!==String(id));write(KEYS.invoices,invoices);logActivity('Deleted invoice',i.number);updateEverything()}
function invoiceMarkup(i){return `<div class="invoice-paper"><div class="invoice-head"><div><div class="invoice-brand">${esc(settings.businessName||'BizPilot')}</div><div>${esc(settings.address||'')}${settings.phone?' · '+esc(settings.phone):''}${settings.email?' · '+esc(settings.email):''}</div></div><div><strong>${esc(i.number)}</strong><div>${fmtDate(i.date)}</div></div></div><div class="invoice-to"><strong>Bill To</strong><div>${esc(i.customerName||'Walk-in / Unassigned')}</div></div><table><thead><tr><th>Item</th><th>Qty</th><th>Price</th><th>Total</th></tr></thead><tbody>${i.items.map(x=>`<tr><td>${esc(x.name)}</td><td>${x.qty}</td><td>${money(x.price)}</td><td>${money(x.qty*x.price)}</td></tr>`).join('')}</tbody></table><div class="invoice-print-totals"><div>Subtotal <strong>${money(i.subtotal)}</strong></div><div>Tax <strong>${money(i.tax)}</strong></div><div>Total <strong>${money(i.total)}</strong></div><div>Status <strong>${esc(i.status)}</strong></div></div><p>${esc(i.notes||'')}</p><footer>${esc(settings.receiptFooter||'Thank you for your business.')}</footer></div>`}
function printInvoice(id){const i=invoices.find(x=>String(x.id)===String(id));if(!i)return;const w=window.open('','_blank','width=800,height=900');if(!w)return alert('Please allow pop-ups to print the invoice.');w.document.write(`<html><head><title>${esc(i.number)}</title><style>body{font-family:Arial,sans-serif;padding:35px;color:#111}.invoice-paper{max-width:720px;margin:auto}.invoice-head{display:flex;justify-content:space-between;border-bottom:2px solid #111;padding-bottom:18px}.invoice-brand{font-size:25px;font-weight:800}.invoice-to{padding:22px 0}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid #ddd}.invoice-print-totals{margin-left:auto;max-width:300px;margin-top:20px}.invoice-print-totals div{display:flex;justify-content:space-between;padding:7px;border-bottom:1px solid #eee}.invoice-print-totals div:last-child{font-size:18px;border-bottom:2px solid #111}footer{margin-top:45px;border-top:1px solid #ddd;padding-top:15px;color:#666}</style></head><body>${invoiceMarkup(i)}<script>window.onload=()=>{window.print()}<\/script></body></html>`);w.document.close()}
function openStaffModal(id=''){ $('staffEditId').value=id||'';if(id){const s=staff.find(x=>String(x.id)===String(id));if(!s)return;$('staffName').value=s.name;$('staffRole').value=s.role;$('staffPhone').value=s.phone||'';$('staffStatus').value=s.status||'Active';$('staffNotes').value=s.notes||''}else{$('staffName').value='';$('staffRole').value='Sales';$('staffPhone').value='';$('staffStatus').value='Active';$('staffNotes').value=''}$('staffModal').classList.add('show')}
function closeStaffModal(){$('staffModal').classList.remove('show')}
function saveStaff(e){e.preventDefault();const id=$('staffEditId').value,name=$('staffName').value.trim();if(!name)return alert('Staff name is required.');const d={name,role:$('staffRole').value,phone:$('staffPhone').value.trim(),status:$('staffStatus').value,notes:$('staffNotes').value.trim(),updatedAt:new Date().toISOString()};if(id){Object.assign(staff.find(x=>String(x.id)===String(id)),d)}else staff.unshift({id:uid('stf'),...d,createdAt:new Date().toISOString()});write(KEYS.staff,staff);logActivity(id?'Edited staff':'Added staff',name);closeStaffModal();updateEverything()}
function deleteStaff(id){const s=staff.find(x=>String(x.id)===String(id));if(!s)return;if(!confirm(`Delete ${s.name}?`))return;staff=staff.filter(x=>String(x.id)!==String(id));write(KEYS.staff,staff);logActivity('Deleted staff',s.name);updateEverything()}
function saveBusinessProfile(){settings.businessName=$('businessNameInput').value.trim()||'BizPilot';settings.phone=$('businessPhoneInput').value.trim();settings.email=$('businessEmailInput').value.trim();settings.address=$('businessAddressInput').value.trim();settings.currency=$('currencyInput').value;settings.receiptFooter=$('receiptFooterInput').value.trim();write(KEYS.settings,settings);logActivity('Updated business profile',settings.businessName);alert('Business settings saved.');updateEverything()}
function savePreferences(){settings.defaultLowStock=Math.max(0,Math.floor(Number($('defaultLowStockInput').value)||0));settings.taxRate=Math.min(100,Math.max(0,Number($('taxRateInput').value)||0));settings.dailyTarget=Math.max(0,Number($('dailyTargetInput').value)||0);settings.invoicePrefix=$('invoicePrefixInput').value.trim()||'INV';write(KEYS.settings,settings);alert('Preferences saved.');updateEverything()}
function printReport(){showPage('reports');window.print()}
function reportText(){return `${settings.businessName||'BizPilot'} Business Report\nRevenue: ${money(sum(getSales()))}\nSpending: ${money(sum(getExpenses()))}\nProfit: ${money(profit())}\nSales: ${getSales().length}\nExpenses: ${getExpenses().length}\nCustomers: ${customers.length}\nInventory value: ${money(products.reduce((a,p)=>a+p.stock*p.buyingPrice,0))}\nRecommendation: ${recommendation()}`}
async function copyReportSummary(){try{await navigator.clipboard.writeText(reportText());alert('Report summary copied.')}catch(e){alert(reportText())}}
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportBackup(){const payload={format:'BizPilot Backup',version:'4.0',exportedAt:new Date().toISOString(),data:{transactions,customers,products,stockMovements,invoices,staff,activity,settings}};download(`BizPilot_Backup_${today()}.json`,JSON.stringify(payload,null,2))}
function exportTransactionsCSV(){const head=['Date','Type','Name','Amount','Category','Customer','Product','Quantity','Staff','Note'];const rows=transactions.map(t=>[t.date,t.type,t.name,t.amount,t.category||'',customers.find(c=>String(c.id)===String(t.customerId))?.name||'',t.productName||'',t.quantity||'',staff.find(s=>String(s.id)===String(t.staffId))?.name||'',t.note||'']);const csv=[head,...rows].map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');download(`BizPilot_Transactions_${today()}.csv`,csv,'text/csv;charset=utf-8')}
function importBackup(e){const file=e.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);const d=p.data||p;if(!d||!Array.isArray(d.transactions))throw Error('Invalid backup');transactions=d.transactions||[];customers=d.customers||[];products=d.products||[];stockMovements=d.stockMovements||[];invoices=d.invoices||[];staff=d.staff||[];activity=d.activity||[];settings={...settings,...(d.settings||{})};saveAll();alert('Backup imported successfully.');updateEverything()}catch(err){alert('That file is not a valid BizPilot backup.')}};r.readAsText(file);e.target.value=''}
function resetAllData(){if(!confirm('Reset ALL BizPilot data on this device? This cannot be undone unless you have a backup.'))return;Object.values(KEYS).forEach(k=>localStorage.removeItem(k));location.reload()}
function clearAllTransactions(){if(!transactions.length)return alert('There are no transactions to clear.');if(!confirm('Delete all transactions? Inventory stock will NOT be automatically restored. Export a backup first if needed.'))return;transactions=[];write(KEYS.transactions,transactions);logActivity('Cleared transactions','All transaction records removed');updateEverything()}
function focusGlobalSearch(){ $('searchModal').classList.add('show');$('globalSearchInput').value='';renderGlobalSearch();setTimeout(()=>$('globalSearchInput').focus(),80)}
function closeSearch(){$('searchModal').classList.remove('show')}
function renderGlobalSearch(){const q=($('globalSearchInput').value||'').trim().toLowerCase();if(!q){$('globalSearchResults').innerHTML='<div class="empty-state">Type a name, product, customer or invoice number.</div>';return}const results=[];transactions.filter(t=>`${t.name} ${t.note||''}`.toLowerCase().includes(q)).slice(0,8).forEach(t=>results.push({title:t.name,sub:`${t.type} · ${money(t.amount)} · ${fmtDate(t.date)}`,page:t.type==='Sale'?'sales':'expenses'}));products.filter(p=>`${p.name} ${p.notes||''}`.toLowerCase().includes(q)).slice(0,6).forEach(p=>results.push({title:p.name,sub:`Product · ${p.stock} in stock`,page:'inventory'}));customers.filter(c=>`${c.name} ${c.phone||''} ${c.email||''}`.toLowerCase().includes(q)).slice(0,6).forEach(c=>results.push({title:c.name,sub:`Customer · ${money(customerStats(c.id).revenue)} spent`,page:'customers'}));invoices.filter(i=>`${i.number} ${i.customerName||''}`.toLowerCase().includes(q)).slice(0,6).forEach(i=>results.push({title:i.number,sub:`Invoice · ${money(i.total)}`,page:'invoices'}));$('globalSearchResults').innerHTML=results.length?results.map(r=>`<div class="search-result" onclick="closeSearch();showPage('${r.page}')"><strong>${esc(r.title)}</strong><span>${esc(r.sub)}</span></div>`).join(''):'<div class="empty-state">No matching records.</div>'}
let remoteAccount=null;
let apiAvailable=false;
let syncTimer=null;
const API_BASE='';
function authMessage(msg,type='info'){const el=$('authMessage');if(!el)return;el.textContent=msg||'';el.className='auth-message '+type}
function getSession(){return read('bizpilot_local_session',null)}
function setLocalSession(profile){profile?write('bizpilot_local_session',{userId:profile.id,email:profile.email}):localStorage.removeItem('bizpilot_local_session')}
function getSubscription(){
  const sub=remoteAccount?.subscription;
  if(sub)return sub;
  return read(SUB_KEY,{status:'free',plan:null,startedAt:null,expiresAt:null});
}
function isProActive(){const sub=getSubscription();return sub.status==='pro'&&sub.expiresAt&&new Date(sub.expiresAt)>new Date()}
function showAuthPanel(which){$('loginPanel').classList.toggle('hidden',which!=='login');$('registerPanel').classList.toggle('hidden',which!=='register')}
async function api(path,options={}){
  const res=await fetch(API_BASE+path,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});
  let data={};try{data=await res.json()}catch(e){}
  if(!res.ok)throw new Error(data.error||`Request failed (${res.status})`);
  return data;
}
function cacheAccount(data){remoteAccount=data.user||data;setLocalSession(remoteAccount);write('bizpilot_cached_profile',remoteAccount);if(remoteAccount.subscription)write(SUB_KEY,remoteAccount.subscription)}
function localDataPayload(){return {transactions,customers,products,stockMovements,invoices,staff,activity,settings}}
function applyServerData(d){
  if(!d||typeof d!=='object')return;
  transactions=Array.isArray(d.transactions)?d.transactions:[];
  customers=Array.isArray(d.customers)?d.customers:[];
  products=Array.isArray(d.products)?d.products:[];
  stockMovements=Array.isArray(d.stockMovements)?d.stockMovements:[];
  invoices=Array.isArray(d.invoices)?d.invoices:[];
  staff=Array.isArray(d.staff)?d.staff:[];
  activity=Array.isArray(d.activity)?d.activity:[];
  if(d.settings&&typeof d.settings==='object')settings={...settings,...d.settings};
  saveAll(false);
}
async function pullServerData(){
  if(!apiAvailable)return;
  try{const r=await api('/api/data');if(r.data){const local=localDataPayload();const serverEmpty=!r.data.transactions?.length&&!r.data.customers?.length&&!r.data.products?.length&&!r.data.invoices?.length&&!r.data.staff?.length;const localHas=local.transactions.length||local.customers.length||local.products.length||local.invoices.length||local.staff.length;if(serverEmpty&&localHas){await syncToServer()}else applyServerData(r.data)}}catch(e){console.warn('BizPilot cloud load:',e.message)}
}
function scheduleSync(){
  if(!apiAvailable||!remoteAccount)return;
  clearTimeout(syncTimer);syncTimer=setTimeout(syncToServer,700);
}
async function syncToServer(){
  if(!apiAvailable||!remoteAccount)return;
  try{await api('/api/data',{method:'PUT',body:JSON.stringify(localDataPayload())});setConnectionState(true)}catch(e){console.warn('BizPilot cloud sync:',e.message);setConnectionState(false)}
}
function saveAll(sync=true){
  write(KEYS.transactions,transactions);write(KEYS.customers,customers);write(KEYS.inventory,products);write(KEYS.stock,stockMovements);write(KEYS.invoices,invoices);write(KEYS.staff,staff);write(KEYS.activity,activity);write(KEYS.settings,settings);
  if(sync)scheduleSync();
}
function setConnectionState(cloud){
  const dot=$('connectionDot'),text=$('connectionText');if(!dot||!text)return;
  const online=navigator.onLine;
  dot.style.background=online?'#22c55e':'#f59e0b';
  text.textContent=online?(cloud?'Online · Cloud synced':'Online · Local cache'):'Offline · Local data';
}
async function registerAccount(e){
  e.preventDefault();
  const name=$('registerName').value.trim(),email=$('registerEmail').value.trim().toLowerCase(),p=$('registerPassword').value,p2=$('registerPassword2').value;
  if(p!==p2){authMessage('Passwords do not match.','error');return;}
  if(!navigator.onLine){authMessage('Connect to the internet to create your online account.','error');return;}
  authMessage('Creating your account…','info');
  try{
    const r=await api('/api/auth/register',{method:'POST',body:JSON.stringify({name,email,password:p})});
    cacheAccount(r);apiAvailable=true;
    $('registerName').value='';$('registerEmail').value='';$('registerPassword').value='';$('registerPassword2').value='';
    hideAuthGate();loadAll();await pullServerData();updateEverything();showPage('account');alert('Account created successfully.');
  }catch(err){authMessage(err.message,'error')}
}
async function loginAccount(e){
  e.preventDefault();
  const email=$('loginEmail').value.trim().toLowerCase(),p=$('loginPassword').value;
  if(!navigator.onLine){authMessage('Connect to the internet to log in.','error');return;}
  authMessage('Signing you in…','info');
  try{
    const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email,password:p})});
    cacheAccount(r);apiAvailable=true;hideAuthGate();loadAll();await pullServerData();updateEverything();
  }catch(err){authMessage(err.message,'error')}
}
function hideAuthGate(){$('authGate').classList.add('hidden')}
async function logoutAccount(){try{if(navigator.onLine)await api('/api/auth/logout',{method:'POST'})}catch(e){}remoteAccount=null;apiAvailable=false;setLocalSession(null);location.reload()}
function currentAccount(){return remoteAccount||read('bizpilot_cached_profile',null)}
async function loadRemoteSession(){
  if(!navigator.onLine)return false;
  try{const r=await api('/api/auth/me');cacheAccount(r);apiAvailable=true;return true}catch(e){apiAvailable=false;return false}
}
function renderAccount(){
  const a=currentAccount();if(!a)return;
  const sub=getSubscription(),active=isProActive();
  $('accountName').value=a.name||'';$('accountEmail').value=a.email||'';
  $('accountPlanBadge').textContent=active?'PRO PLAN':'FREE PLAN';$('subscriptionStatus').textContent=active?`Pro ${sub.plan||''} plan is active`:'Free plan';
  $('subscriptionDetails').innerHTML=active?`<div class="table-row"><span>Plan</span><span>${esc(sub.plan||'Pro')}</span></div><div class="table-row"><span>Expires</span><span>${fmtDate(String(sub.expiresAt).slice(0,10))}</span></div><div class="table-row"><span>Payment</span><span>${esc(sub.provider||'Pesapal')}</span></div>`:'<div class="empty-state">No active Pro subscription. Choose Monthly or Annual to continue to Pesapal checkout.</div>';
}
async function saveAccountProfile(){
  const a=currentAccount();if(!a)return;const name=$('accountName').value.trim();if(!name)return alert('Name is required.');
  if(!apiAvailable)return alert('Connect to the internet to update your account profile.');
  try{const r=await api('/api/auth/profile',{method:'PUT',body:JSON.stringify({name})});cacheAccount(r);alert('Profile saved.');updateEverything()}catch(e){alert(e.message)}
}
async function requestProPlan(plan){
  const a=currentAccount();if(!a)return;
  if(!apiAvailable||!navigator.onLine)return alert('Connect to the internet to start Pro checkout.');
  try{
    const r=await api('/api/payments/create',{method:'POST',body:JSON.stringify({plan})});
    if(r.redirect_url){if(r.order_tracking_id)sessionStorage.setItem('bizpilot_pending_tracking',r.order_tracking_id);window.location.href=r.redirect_url;}else alert('Pesapal checkout could not be created.');
  }catch(e){alert(e.message)}
}
function showUpgradeMessage(){showPage('account')}
document.addEventListener('click',e=>{['transactionModal','productModal','stockModal','customerModal','invoiceModal','staffModal','searchModal'].forEach(id=>{if(e.target===$(id))$(id).classList.remove('show')})});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();focusGlobalSearch()}if(e.key==='Escape'){document.querySelectorAll('.modal.show').forEach(m=>m.classList.remove('show'))}});
function updateConnectionStatus(){setConnectionState(apiAvailable)}
window.addEventListener('online',async()=>{setConnectionState(apiAvailable);if(!apiAvailable&&await loadRemoteSession()){hideAuthGate();await pullServerData();updateEverything()}else await syncToServer()});
window.addEventListener('offline',()=>setConnectionState(false));
document.addEventListener('DOMContentLoaded',async()=>{
  loadAll();
  const remote=await loadRemoteSession();
  if(remote){hideAuthGate();await pullServerData();}
  else if(getSession()&&read('bizpilot_cached_profile',null)){hideAuthGate();remoteAccount=read('bizpilot_cached_profile',null)}
  else $('authGate').classList.remove('hidden');
  if(!$('insightFrom').value){const d=new Date();d.setDate(d.getDate()-6);$('insightFrom').value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
  $('insightTo').value=today();updateEverything();updateConnectionStatus();
  if('serviceWorker' in navigator){navigator.serviceWorker.register('./service-worker.js',{scope:'./'}).catch(error=>console.warn('BizPilot offline service worker:',error))}
  const params=new URLSearchParams(location.search);if(params.get('payment')==='success'){const tracking=params.get('OrderTrackingId')||sessionStorage.getItem('bizpilot_pending_tracking');history.replaceState({},'',location.pathname);if(tracking&&apiAvailable){try{const r=await api('/api/payments/status?trackingId='+encodeURIComponent(tracking));if(r.subscription){remoteAccount.subscription=r.subscription;write(SUB_KEY,r.subscription)}alert(r.subscription?.status==='pro'?'Payment verified. BizPilot Pro is now active.':'Payment received. Pro will activate after Pesapal confirms the transaction.')}catch(e){alert('Payment return received. BizPilot will verify the payment shortly.')}}else alert('Payment return received. BizPilot will verify the payment shortly.');sessionStorage.removeItem('bizpilot_pending_tracking');updateEverything()}
  console.log('BizPilot production build loaded.');
});
async function refreshSubscription(){try{const r=await api('/api/auth/me');cacheAccount(r);updateEverything()}catch(e){}}

